export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const EDIT_HEADING = "EDIT_HEADING"
export const ADD_NEW_CARD = "ADD_NEW_CARD"

export const ADD_NEW_WIDGET = "ADD_NEW_WIDGET"
export const UPADTE_WIDGET_POSITION = "UPADTE_WIDGET_POSITION"
export const UPADTE_WIDGET_SIZE = "UPADTE_WIDGET_SIZE"